function [path,version,versionmatfiles] = toolbox_path() ; 

path = fileparts(fileparts(which('microstate.functions.toolbox_path'))) ; 
version = 'v1.1' ; 

versionmatfiles = {...
    fullfile('+microstate','+external','HCP230','atlas','hcp230.mat') , false ; ...
    fullfile('+microstate','+external','LORETA','LORETA_dipole_positions.mat'), false ; ...
    fullfile('+microstate','+external','LORETA','sLORETA_dipole_positions.mat'), false ; ...
    fullfile('+microstate','+external','fieldtrip','template','anatomy','inflated.mat'), false ; ...
    fullfile('+microstate','+external','fieldtrip','template','atlas','aal.mat'), false ; ...
    fullfile('+microstate','+external','fieldtrip','template','atlas','afni_brick0.mat'), false ;...
    fullfile('+microstate','+external','fieldtrip','template','atlas','afni_brick1.mat'), false ;...
    fullfile('+microstate','+external','fieldtrip','template','atlas','brainnetome.mat'), false ;...
    fullfile('+microstate','+external','fieldtrip','template','layout','biosemi256.mat'), false ; ...
    fullfile('+microstate','+external','fieldtrip','template','layout','CTF151.mat'), false ;...
    fullfile('+microstate','+external','fieldtrip','template','layout','CTF275.mat'), false ;...
    fullfile('+microstate','+external','fieldtrip','template','layout','EEG1005.mat'), false ;...
    fullfile('+microstate','+external','fieldtrip','template','layout','neuromag306.mat'), false ; ...
    fullfile('examples','example1_EEGcanonicalmaps','example1_data.mat'), true ; ...
    fullfile('examples','example2_MEGtopographicERP','example2_data.mat'), true ; ...
    fullfile('examples','example4_GroupAnalysisSourceMEG','example4_data.mat'), true ; ...
    fullfile('examples','example4_GroupAnalysisSourceMEG','layout.mat'), true} ;

for mat = 1:size(versionmatfiles,1)
    
    url = ['https://github.com/plus-microstate/toolbox/raw/master/' versionmatfiles{mat}] ; 
    url = replace(url,filesep,'/') ; 
    url = replace(url,'+','%2B') ; 
    
    versionmatfiles{mat,3} = url ; 
    versionmatfiles{mat,1} = fullfile(fileparts(path),versionmatfiles{mat,1}) ; 
end